# Generated by Django 6.0.8 on 2026-09-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_vlc_play_and_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprofile',
            name='parameters',
            field=models.TextField(blank=True, help_text='Command-line parameters. Use {userAgent}, {streamUrl}, and {channelId} as placeholders.'),
        ),
    ]
