[supervisord]
nodaemon=true
logfile=/run/supervisord.log
logfile_maxbytes=1MB
logfile_backups=1
pidfile=/run/supervisord.pid
childlogdir=/run

[unix_http_server]
file=/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[include]
files = /app/docker/supervisord.d/api-uwsgi.conf /app/docker/supervisord.d/daphne.conf /app/docker/supervisord.d/nginx.conf
