[program:api-uwsgi]
command=nice -n %(ENV_UWSGI_NICE_LEVEL)s setpriv --reuid=%(ENV_POSTGRES_USER)s --regid=%(ENV_POSTGRES_USER)s --init-groups /app/docker/supervisord.d/wait-for-stores.sh %(ENV_VIRTUAL_ENV)s/bin/uwsgi --ini %(ENV_DISPATCHARR_UWSGI_INI)s %(ENV_DISPATCHARR_UWSGI_EXTRA_ARGS)s
directory=/app
environment=HOME="%(ENV_DISPATCHARR_HOME)s",USER="%(ENV_POSTGRES_USER)s"
priority=200
autostart=true
autorestart=true
startretries=20
startsecs=5
stopsignal=TERM
stopwaitsecs=10
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
