[program:celery-default]
command=nice -n %(ENV_CELERY_NICE_LEVEL)s setpriv --reuid=%(ENV_DISPATCHARR_CELERY_USER)s --regid=%(ENV_DISPATCHARR_CELERY_USER)s --init-groups /app/docker/supervisord.d/wait-for-stores.sh celery -A dispatcharr worker -Q celery -n default@%%h --autoscale=6,1 -l %(ENV_CELERY_LOG_LEVEL)s
directory=/app
environment=HOME="%(ENV_DISPATCHARR_CELERY_HOME)s",USER="%(ENV_DISPATCHARR_CELERY_USER)s"
priority=220
autostart=true
autorestart=true
startretries=20
startsecs=5
stopsignal=TERM
stopwaitsecs=30
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
