[program:postgres]
command=%(ENV_PG_BINDIR)s/postgres -D %(ENV_POSTGRES_DIR)s -c port=%(ENV_POSTGRES_PORT)s
user=%(ENV_POSTGRES_USER)s
environment=HOME="%(ENV_DISPATCHARR_HOME)s",USER="%(ENV_POSTGRES_USER)s"
priority=100
autostart=true
autorestart=true
startsecs=5
startretries=20
stopsignal=INT
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
